<a href="https://colab.research.google.com/github/hoangnuthuphuong/Machine_Learning/blob/main/Chuong5_HuanLuyenMoHinh_%26_Loi/C5_BTKN03_Evaluating.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

# 1. Độ chính xác dự đoán nhãn lớp – **Accuracy score**
Đối với bài toán phân lớp (lưu ý: mô hình hồi quy logistic thực chất là mô hình phân lớp) có đặc trưng là vector “nhãn lớp” – y
– chứa các giá trị rời rạc ($y = [y_0; y_1; ... ; y_{m−1}]$ với $y_i ∈ {c_j|j =1̅,k̅})$. Do vậy, các phép đo hiệu năng dựa vào sai số của mô hình hồi quy không áp dụng được trong trường hợp này. Vì vậy, chúng ta có một lớp các phép đo khác chuyên dụng để đánh giá hiệu năng dự đoán của mô hình phân lớp. Trong đó, phép đo độ chính xác – Accuracy – là một trong những phép đo phổ biến nhất.
Cho $y ∈ R^m$ và $ŷ ∈ R^m$ lần lượt là vector “nhãn lớp” thực tế và vector chứa nhãn lớp dự đoán của mô hình phân lớp h. Độ chính xác dự đoán của mô hình h được tính theo công thức sau:

$$accuracy(y, ŷ) =\frac{1}{m} ∑_{i=0}^{m-1}(y_i = ŷ_i)$$

Viết lại công thức:
$$accuracy(y, ŷ) =\frac{1}{m} ∑(y = ŷ)$$

**Lập trình Python**

In [3]:
def acc_score(y, y_hat):
  m = y.shape[0]
  result = (1/m)*np.sum(y == y_hat)
  return result

**Sử dụng sklearn**

In [4]:
from sklearn.metrics import accuracy_score
y_test = np.array([0, 1, 2, 2])
y_hat = np.array([0, 1, 2, 2])

**Kết quả**

In [5]:
print('\tChỉ số Accuracy lập trình Python: ', acc_score(y_test, y_hat))
print('\tSử dụng sklearn, Acc: ',accuracy_score(y_test.flatten(),y_hat.flatten()))

	Chỉ số Accuracy lập trình Python:  1.0
	Sử dụng sklearn, Acc:  1.0


---

# **Các độ đo phổ biến đánh giá hiệu năng mô hình phân lớp**
Ngoài độ đo Accuracy, thư viện sklearn còn cung cấp nhiều độ đo khác dùng để đánh giá hiệu năng của mô hình phân lớp [link](https://scikit-learn.org/stable/modules/model_evaluation.html#classification-metrics). Hãy hoàn thành bảng sau và viết chương trình đánh giá hiệu năng mô hình hồi quy logistic bằng các thang đo mới. Hãy xây dựng bảng như
trên, với yêu cầu:
> Liệt kê tất cả các độ đo phổ biến của mô hình hồi quy theo [tài liệu tham khảo](https://scikit-learn.org/stable/modules/model_evaluation.html#classification-metrics);
- Cột 1: Viết công thức Toán gốc và công thức Toán chuyển đổi theo cú pháp vector/ma trận;
- Cột 2: Tự lập trình Python theo công thức Toán đã chuyển đổi;
- Cột 3: Sử dụng thư viện sklearn.metrics


Các chỉ số **TP, FP, TN, FN** lần lượt có ý nghĩa là :

* TP (True Positive): Tổng số trường hợp dự báo khớp Positive.
* TN (True Negative): Tổng số trường hợp dự báo khớp Negative.
* FP (False Positive): Tổng số trường hợp dự báo các quan sát thuộc nhãn Negative thành Positive.
* FN (False Negative): Tổng số trường hợp dự báo các quan sát thuộc nhãn Positive thành Negative.

## **Độ đo Top k accuracy**
Số liệu này tính toán số lần nhãn chính xác nằm trong số các knhãn hàng đầu được dự đoán (xếp hạng theo điểm số dự đoán)

**CÔNG THỨC**
$$top-k-accuracy(y, \hat{f}) =\frac{1}{m} ∑_{i=0}^{m-1}∑_{j=0}^{k}(\hat{f}_{i,j} = y_i)$$

**Lập trình Python**

In [19]:
def top_k_accuracy(y_test, y_score, k):
  sorted_index = np.argsort(y_score, axis=1)[:, ::-1]
  top_k = sorted_index[:, :k].T
  result = np.sum(y_test == top_k)
  return result

**Sử dụng sklearn**

In [20]:
from sklearn.metrics import top_k_accuracy_score
y_test = np.array([0, 1, 2, 2])
y_score = np.array([[0.5, 0.2, 0.2], 
                    [0.3, 0.4, 0.2],
                    [0.2, 0.4, 0.3],
                    [0.7, 0.2, 0.1]])

**Kết quả**

In [22]:
print('Chỉ số top k accuracy lập trình Python: ',top_k_accuracy(y_test, y_score, 2))
print('\nSử dụng sklearn: ',top_k_accuracy_score(y_test, y_score, k=2, normalize=False))

Chỉ số top k accuracy lập trình Python:  3

Sử dụng sklearn:  3


---

## **Confusion matrix**
Tính toán ma trận nhầm lẫn để đánh giá độ chính xác của phân loại.


**Lập trình Python**

In [11]:
def cfs_matrix(y_test, y_pred):
  y_test = np.array(y_test)
  y_pred = np.array(y_pred)
  class_num = np.unique(y_test).shape[0]
  result = np.zeros((class_num, class_num))
  n = y_test.shape[0]
  for i in range(n):
    result[y_test[i], y_pred[i]] += 1
  return result

**Sử dụng sklearn**

In [10]:
from sklearn.metrics import confusion_matrix
y_test = [2, 0, 2, 2, 0, 1]
y_pred = [0, 0, 2, 2, 0, 2]

**Kết quả**

In [12]:
print('Sử dụng sklearn:\n',confusion_matrix(y_test, y_pred))
print('\nConfusion matrix - lập trình Python: \n',cfs_matrix(y_test, y_pred))

Sử dụng sklearn:
 [[2 0 0]
 [0 0 1]
 [1 0 2]]

Confusion matrix - lập trình Python: 
 [[2. 0. 0.]
 [0. 0. 1.]
 [1. 0. 2.]]


---

## **Độ đo Precision**
Để tính độ chính xác. Độ chính xác là tỷ lệ trong đó là số lượng dương tính thật và số lượng dương tính giả. Độ chính xác là khả năng của bộ phân loại không dán nhãn là dương tính cho một mẫu âm tính.

Giá trị tốt nhất là 1 và giá trị xấu nhất là 0.

**CÔNG THỨC:**
$$Precision=\frac{TP}{TP + FP}$$

**Lập trình Python**

In [26]:
def precision_sc(y_test, y_pred, positive = None):
  cfs = confusion_matrix(y_test, y_pred)
  if positive:
    return cfs[positive,positive]/np.sum(cfs[:, positive])
  else:
    class_num = np.unique(y_test).shape[0]
    result = []
    for i in range(class_num):
      result.append(cfs[i,i]/np.sum(cfs[:, i]))
    return np.array(result)

**Sử dụng sklearn**

In [29]:
from sklearn.metrics import precision_score
y_test = [0, 0, 0, 1, 1, 1, 1, 1]
y_pred = [0, 1, 0, 1, 0, 1, 0, 1]

**Kết quả**

In [31]:
print('Sử dụng sklearn:\n',precision_score(y_test, y_pred))
print('\nPrecision_score - lập trình Python: \n',precision_sc(y_test, y_pred, 1))

Sử dụng sklearn:
 0.75

Precision_score - lập trình Python: 
 0.75


---

## **Độ đo Recall**
Dùng để tính toán thu hồi. Recall cao đồng nghĩa với tỉ lệ bỏ sót các điểm (TP +FN) là thấp.

**CÔNG THỨC**
$$Recall=\frac{TP}{TP+FN}$$


**Lập trình Python**

In [32]:
def recall_sc(y_test, y_pred, positive=None):
  cfs = confusion_matrix(y_test, y_pred)
  if positive:
    return cfs[positive,positive]/np.sum(cfs[positive])
  else:
    class_num = np.unique(y_test).shape[0]
    result = []
    for i in range(class_num):
      result.append(cfs[i,i]/np.sum(cfs[i]))
    return np.array(result)

**Sử dụng sklearn**

In [33]:
from sklearn.metrics import recall_score
y_test = [0, 0, 0, 1, 1, 1, 1, 1]
y_pred = [0, 1, 0, 1, 0, 1, 0, 1]

**KẾT QUẢ**

In [34]:
print('Sử dụng sklearn:\n',recall_score(y_test, y_pred))
print('\nRecall score - lập trình Python: \n',recall_sc(y_test, y_pred, 1))

Sử dụng sklearn:
 0.6

Recall score - lập trình Python: 
 0.6


---

## **Độ đo balanced accuracy**
Tính toán độ chính xác cân bằng.
Độ chính xác cân bằng trong các vấn đề phân loại nhị phân và đa lớp để xử lý các bộ dữ liệu không cân bằng. Nó được định nghĩa là mức thu hồi trung bình thu được trên mỗi lớp.

Giá trị tốt nhất là 1 và giá trị xấu nhất là 0 khi `adjusted=False.`

CÔNG THỨC:
$$balanced-accuracy(y, \hat{y},w) = \frac{1}{∑ \hat{w_i}} ∑_i 1(\hat{y_i}=y_i)\hat{w_i}$$ 

với $$\hat{w_i} = \frac{w_i}{∑_j 1(y_j=y_i)w_j}$$


CÔNG THỨC CHUYỂN ĐỔI:
$$balanced-accuracy = \frac{1}{2} (\frac{TP}{TP + FN} + \frac{TN}{TN+FP})$$

* $\frac{TP}{TP + FN}$: Tỉ lệ số điểm True Positive trong số những điểm thật sự là Positive


* $\frac{TN}{TN+FP}$: Tỉ lệ số điểm True Negative trong số những điểm thật sự là Negative

Hai giá trị trên mà cao nghĩa là tỉ lệ bỏ xót các điểm đúng thấp.

**Lập trình Python**

In [40]:
def true_negative_rate(y_test, y_pred, positive=None):
  cfs = confusion_matrix(y_test, y_pred)
  sum_cross = np.sum(cfs.diagonal())
  if positive:
    tp = cfs[positive,positive]
    tn = sum_cross - tp
    fp = np.sum(cfs[:,positive]) - tp
    return tn/(tn+fp)
  else:
    class_num = np.unique(y_test).shape[0]
    result = []
    for i in range(class_num):
      tp = cfs[i,i]
      tn = sum_cross - tp
      fp = np.sum(cfs[:,i]) - tp
      result.append(tn/(tn+fp))
    return np.array(result)

In [41]:
def balanced_accuracy_sc(y_test, y_pred, positive=None):
  temp1 = recall_sc(y_test, y_pred, positive)
  temp2 = true_negative_rate(y_test, y_pred, positive)
  return 1/2 * (temp1 + temp2)

**Sử dụng sklearn**

In [42]:
from sklearn.metrics import balanced_accuracy_score
y_test = [0, 0, 0, 1, 1, 1, 1, 1]
y_pred = [0, 1, 0, 1, 0, 1, 0, 1]

**KẾT QUẢ**

In [105]:
print('Sử dụng sklearn:\n',balanced_accuracy_score(y_test, y_pred))
print('\nBalanced accuracy score - lập trình Python: \n',balanced_accuracy_sc(y_test, y_pred, 1))

Sử dụng sklearn:
 0.6333333333333333

Balanced accuracy score - lập trình Python: 
 0.6333333333333333


---

## **Độ đo F1 (F-measure)**
Tính điểm F1, còn được gọi là điểm F cân bằng hoặc thước đo F.

Điểm F1 có thể được hiểu là trung bình điều hòa của độ chính xác và khả năng thu hồi, trong đó điểm F1 đạt giá trị tốt nhất là 1 và điểm kém nhất là 0. Mức độ đóng góp tương đối của độ chính xác và khả năng thu hồi vào điểm F1 là như nhau. **Công thức tính**:

$$F1={2}\times{\frac{{Precision}\times{Recall}}{Precision+Recall}}$$

**Lập trình Python**

In [147]:
def f1_sc(y_test, y_pred, positive=None):
  precision = precision_score(y_test, y_pred)
  recall = recall_score(y_test, y_pred)
  result = 2 * (precision * recall) / (precision + recall)
  return result

**Sử dụng sklearn**

In [148]:
from sklearn.metrics import f1_score
y_test = [0, 0, 0, 1, 1, 1, 1, 1]
y_pred = [0, 1, 0, 1, 0, 1, 0, 1]


**KẾT QUẢ**

In [149]:
print('Sử dụng sklearn:\n',f1_score(y_test, y_pred))
print('\nF-measure - lập trình Python: \n',f1_sc(y_test, y_pred,1))

Sử dụng sklearn:
 0.6666666666666665

F-measure - lập trình Python: 
 0.6666666666666665


---

## **Viết chương trình đánh giá hiệu năng phân lớp của mô hình hồi quy logistic bằng các chỉ số khác ngoài Accuracy.**

In [ ]:
import numpy as np
import os
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import MinMaxScaler, StandardScaler

In [ ]:
def readData(filePath: str, filename: str):
    data = np.loadtxt(os.path.join(filePath, filename), delimiter = ',')
    X = data[:,:-1]
    y = data[:, -1]
    m = X.shape[0]
    n = X.shape[1]
    X = np.reshape(X, (m,n))
    y = np.reshape(y, (m,1))
    #Them cot x0 = 1 vao X
    x0 = np.ones((m,1))
    X = np.column_stack([x0, X])
    return X, y

In [ ]:
def featureVectorScaling(data):
    avg = np.mean(data)
    sln = data.max()
    snn = data.min()
    data_scl = (data - avg)/(sln - snn)
    print(data_scl[1])
    return data_scl

In [ ]:
def normalizeData(X):
    X_scl = X[:, 0]
    for i in range(1, X.shape[1]):
        scl = featureVectorScaling(X[:, i])
        X_scl = np.column_stack([X_scl, scl])
    return X_scl

In [ ]:
def sigmoid(X, w):
    result = 1/(1 + np.exp(-np.dot(X, w)))
    return result

Hàm mất mát

In [ ]:
def loss(X, y, w):
    m = y.shape[0]
    result = (-1/m)*np.sum(np.dot(y.T, np.log(sigmoid(X, w))) + np.dot((1 - y).T, np.log(1 - sigmoid(X, w))))
    return result

Hàm Gradient

In [ ]:
def gradient(X, y, w):
    m = X.shape[0]
    result = (1/m)*np.dot(X.T, sigmoid(X, w) - y)
    return result

In [ ]:
def gradientDescent(X, y, w, alpha, n_iters):
    w_optimal = w.copy()
    J_history = []
    for i in range(n_iters):
        w_optimal = w_optimal - alpha*gradient(X, y, w_optimal)
        J_history.append(loss(X, y, w_optimal))
    return w_optimal, J_history

### **Hàm các độ đo đánh giá hiệu năng mô hình phân lớp**

Hàm Predict

In [ ]:
# Hàm dự đoán nếu y_pred >=0.5 làm tròn thành 1, ngược lại là 0
def predict(y_pred):
    return np.rint(y_pred)

Hàm tính Accuracy Score

In [ ]:
def acc_score(y, y_hat):
    m = y.shape[0]
    result = (1/m)*np.sum(y == y_hat)
    return  result

Hàm Balanced accuracy


In [111]:
def true_negative_rate(y_test, y_pred, positive=None):
  cfs = confusion_matrix(y_test, y_pred)
  sum_cross = np.sum(cfs.diagonal())
  if positive:
    tp = cfs[positive,positive]
    tn = sum_cross - tp
    fp = np.sum(cfs[:,positive]) - tp
    return tn/(tn+fp)
  else:
    class_num = np.unique(y_test).shape[0]
    result = []
    for i in range(class_num):
      tp = cfs[i,i]
      tn = sum_cross - tp
      fp = np.sum(cfs[:,i]) - tp
      result.append(tn/(tn+fp))
    return np.array(result)

def balanced_accuracy_sc(y_test, y_pred, positive=None):
  temp1 = recall_sc(y_test, y_pred, positive)
  temp2 = true_negative_rate(y_test, y_pred, positive)
  return 1/2 * (temp1 + temp2)

Hàm Top k accuracy

In [137]:
def top_k_accuracy(y_test, y_pred, k):
  sorted_index = np.argsort(y_pred, axis=1)[:, ::-1]
  top_k = sorted_index[:, :k].T
  result = np.sum(y_test == top_k)
  return result

Hàm Recall


In [143]:
def recall_sc(y_test, y_pred, positive=None):
  cfs = confusion_matrix(y_test, y_pred)
  if positive:
    return cfs[positive,positive]/np.sum(cfs[positive])
  else:
    class_num = np.unique(y_test).shape[0]
    result = []
    for i in range(class_num):
      result.append(cfs[i,i]/np.sum(cfs[i]))
    return np.array(result)

Hàm F measure

In [150]:
def f1_sc(y_test, y_pred, positive=None):
  precision = precision_score(y_test, y_pred)
  recall = recall_score(y_test, y_pred)
  result = 2 * (precision * recall) / (precision + recall)
  return result

### **Hàm main**

In [154]:
def main():
    X, y = readData('/content/drive/MyDrive/Classroom/Học máy 1 Phần cơ sở', 'ex2data1.txt')
    X = normalizeData(X)
    n = X.shape[1]
    w = np.zeros((n, 1))
    alpha = 0.01
    n_iters = 2000
    #Chia train - test
    X_train, X_test, y_train, y_test = train_test_split(X, y,
                                                        test_size=0.30,
                                                        random_state=15)
    w_opt, J_hist = gradientDescent(X_train, y_train, w, alpha, n_iters)
    print("\n KẾT QUẢ HUẤN LUYỆN MÔ HÌNH ")
    print('\n\tTrọng số tối ưu là:\n', w_opt)
    print('\tGiá trị Loss tối ưu là:\n', J_hist[-1])
    print('\n\n KẾT QUẢ CỦA MÔ HÌNH ĐÁNH GIÁ HIỆU NĂNG PHÂN LỚP:')
    y_pred = predict(sigmoid(X_test, w_opt))
    print('\n\tMột số kết quả dự đoán:\n', y_pred[:5,:])
    print('\tChỉ số Accuracy: ', acc_score(y_test, y_pred))
    print('\tSử dụng sklearn, Acc: ', accuracy_score(y_test.flatten(), y_pred.flatten()))
    print('\tChỉ số Balanced Accuracy: ', balanced_accuracy_sc(y_test, y_pred))
    print('\tChỉ số Top k Accuracy: ',top_k_accuracy(y_test, y_pred,1))
    print('\tChỉ số Recall: ',recall_sc(y_test, y_pred,1))
    print('\tChỉ số F1',f1_sc(y_test, y_pred))

if __name__ == "__main__":
    main()

-0.5067801656080071
-0.3270580397857178

 KẾT QUẢ HUẤN LUYỆN MÔ HÌNH 

	Trọng số tối ưu là:
 [[0.32456757]
 [1.22630673]
 [1.26036079]]
	Giá trị Loss tối ưu là:
 0.526112202365058


 KẾT QUẢ CỦA MÔ HÌNH ĐÁNH GIÁ HIỆU NĂNG PHÂN LỚP:

	Một số kết quả dự đoán:
 [[1.]
 [1.]
 [1.]
 [1.]
 [1.]]
	Chỉ số Accuracy:  0.8666666666666667
	Sử dụng sklearn, Acc:  0.8666666666666667
	Chỉ số Balanced Accuracy:  [0.8 0.8]
	Chỉ số Top k Accuracy:  300
	Chỉ số Recall:  1.0
	Chỉ số F1 0.9090909090909091
