<a href="https://colab.research.google.com/github/hoangnuthuphuong/Machine_Learning/blob/main/Chuong1_NhapMonHocMay/BTVN2_Vector_Matrix_Tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# **CÁC PHÉP TOÁN VỚI VECTOR**|

Phép cộng 2 vector $x,y ∈ R^n$

> $f(x, y): R^n + R^n → R^n$

> $ f(x,y) = x + y, ∀x,y ∈ R^n$

$
\begin{bmatrix}
x_0 \\
x_1 \\ 
\ldots \\
x_{n-1}\\
\end{bmatrix}$ + 
$\begin{bmatrix}
y_0 \\
y_1 \\ 
\ldots \\
y_{n-1}\\
\end{bmatrix}$ =
$\begin{bmatrix}
x_0+y_0 \\
x_1+y_1 \\ 
\ldots \\
x_{n-1}+y_{n-1}\\
\end{bmatrix}$

Ví dụ:
$\begin{bmatrix}
1\\
2\\
3
\end{bmatrix}$ +
$\begin{bmatrix}
1\\
2\\
3
\end{bmatrix}$ =
$\begin{bmatrix}
2\\
4\\
6
\end{bmatrix}$




In [ ]:
# Cộng 2 vector (ndarray 1 chiều) trong Python 
x = np.array([1,2,3,4]) 
y = np.array([5,3,2,1]) 
z = x + y 
print(z) 
print(z.ndim) 
print(z.shape)

[6 5 5 5]
1
(4,)


Phép nhân 1 đại lượng vô hướng với 1 vector: $λ ∈ R, x ∈ R:$
> $f(λ,x): R^n → R^n$

$λ.\begin{bmatrix}
x_0 \\
x_1 \\ 
\ldots \\
x_{n-1}\\
\end{bmatrix}$ =
$\begin{bmatrix}
λ.x_0 \\
λ.x_1 \\ 
\ldots \\
λ.x_{n-1}\\
\end{bmatrix}$


In [ ]:
# Phép nhân đại lượng vô hướng với vector trong Python x = np.array([1,2,3,4]) 
a = 15 
z = a*x 
print(z) 
print(z.ndim) 
print(z.shape)

[15 30 45 60]
1
(4,)


Phép tích vô hướng 2 vector (thường gọi là **dot product**), $y ∈ R^n$

> $f(x, y): R^n . R^n → R$

> $f(x, y) = ∑_{i=1}^n x_i × y_i$

Ví dụ:
$\begin{bmatrix}
1\\
2\\
3
\end{bmatrix}$ +
$\begin{bmatrix}
1\\
2\\
3
\end{bmatrix}$ = $1.1 + 2.2 + 3.3 = 14$

In [ ]:
# Tích vô hướng 2 vector (ndarray 1 chiều) trong Python x = np.array([1,2,3,4]) 
y = np.array([5,3,2,1]) 
x = np.array([1,2,3,4])
z = np.dot(x,y) #hoặc z = x.dot(y) 
print(z) 

21


Phép tích hữu hướng **(cross product)** 2 vector (lưu ý số chiều vector trong trường hợp này ≤ 3).

$\begin{bmatrix}
x_1\\
x_2\\
x_3
\end{bmatrix}$ ⊗ $\begin{bmatrix}
y_1\\
y_2\\
y_3
\end{bmatrix}$ =
$\begin{bmatrix}{
\begin{vmatrix}
x_1 & y_1\\
x_2 & y_2\\
\end{vmatrix} \\
\begin{vmatrix}
x_0 & y_0\\
x_2 & y_2\\
\end{vmatrix} \\ 
\begin{vmatrix}
x_0 & y_0\\
x_1 & y_1\\
\end{vmatrix}}
\end{bmatrix}$

In [ ]:
# Tích hữu hướng (cross product) 2 vector trong Python
x = np.array([1,2,3])
y = np.array([3,2,1])
z = np.cross(x, y)
print(z)
print(z.ndim)
print(z.shape)

[-4  8 -4]
1
(3,)


Phép nhân các phần tử có vị trí tương ứng (elementwise multiplication) 2 vector:
> $f(x, y): R^n ∘ R^n → R^n$
> $x°y = [x_0. y_0; x_1. y_1; ⋯ ; x_{n−1}. y_{n−1}]$

Lưu ý: phép nhân này được sử dụng rất nhiều trong lĩnh vực Học
máy và Học sâu.

In [ ]:
# Phép nhân các phần tử có vị trí tương ứng - elementwise multiplication
x = np.array([1,2,3,4])
y = np.array([5,3,2,1])
z = x*y #hoặc z = np.multiply(x, y)
print(z)
print(z.ndim)
print(z.shape)

[5 6 6 4]
1
(4,)


# **CÁC PHÉP TOÁN VỚI MA TRẬN**

Phép cộng 2 ma trận $X,Y ∈ R^{m×n}:$
> $f(X, Y): R^{m×n} → R^{m×n}$

$\begin{bmatrix}
x_{11} & \ldots & x_{1n}\\
\vdots & \ddots & \vdots \\ 
x_{m1} & \ldots & x_{mn}
\end{bmatrix}$ + 
$\begin{bmatrix}
y_{11} & \ldots & y_{1n}\\
\vdots & \ddots & \vdots \\ 
y_{m1} & \ldots & y_{mn}
\end{bmatrix}$ = 
$\begin{bmatrix}
x_{11}+y_{11} & \ldots & y_{1n}+x_{1n}\\
\vdots & \ddots & \vdots \\ 
x_{m1}+y_{m1} & \ldots & x_{mn}+y_{mn}
\end{bmatrix}$ + 

In [ ]:
# Cộng 2 ma trậntrận
X = np.array([1,2,3,4,5,6]).reshape((2,3))
Y = np.array([6,5,4,3,2,1]).reshape((2,3))
Z = X + Y
print(Z)
print(Z.ndim, '; ', Z.shape)

[[7 7 7]
 [7 7 7]]
2 ;  (2, 3)


Phép nhân ma trận với 1 đại lượng vô hướng $λ ∈ R, X ∈ R^{m*n}$
> $f(λ,x): R^{n*m} → R^{n*m}$

$λ.\begin{bmatrix}
x_{11} & \ldots & x_{1n}\\
\vdots & \ddots & \vdots \\ 
x_{m1} & \ldots & x_{mn}
\end{bmatrix}$ = 
$\begin{bmatrix}
λ.x_{11} & \ldots & λ.x_{1n}\\
\vdots & \ddots & \vdots \\ 
λ.x_{m1} & \ldots & λ.x_{mn}
\end{bmatrix}$

In [ ]:
X = np.array([1,2,3,4,5,6]).reshape((2,3))
a = 2
Z = a*X
print(Z)
print(Z.ndim, '; ', Z.shape)

[[ 2  4  6]
 [ 8 10 12]]
2 ;  (2, 3)


Phép chuyển vị ma trận **(transpose)**:$X ∈ R^{m*n}$
> $f(X): R^{m×n} → R^{n×m}$

> $X → X^T$

In [ ]:
# Phép chuyển vị
X = np.array([1,2,3,4,5,6]).reshape((2,3))
Z = X.T
print(Z)
print(Z.ndim, '; ', Z.shape)

[[1 4]
 [2 5]
 [3 6]]
2 ;  (3, 2)


Phép nhân 2 ma trận:$X ∈ R^{m*n}, Y∈ R^{n*k} $
> $f(X,Y): R^{m×n} * R^{n×k}→ R^{n×k}$

$\begin{bmatrix}
x_{11} & \ldots & x_{1n}\\
\vdots & \ddots & \vdots \\ 
x_{m1} & \ldots & x_{mn}
\end{bmatrix}$
$\begin{bmatrix}
y_{11} & \ldots & y_{1k}\\
\vdots & \ddots & \vdots \\ 
y_{n1} & \ldots & y_{nk}
\end{bmatrix}$ 

In [ ]:
X = np.array([1,2,3,4,5,6]).reshape((2,3))
Y = np.array([6,5,4,3,2,1]).reshape((3,2))
Z = np.dot(X,Y)
print(Z)
print(Z.ndim, '; ', Z.shape)

[[20 14]
 [56 41]]
2 ;  (2, 2)


Phép nhân các phần tử có vị trí tương ứng (elementwise multiplication hay còn gội là **Hadamard product**) của 2 ma trận:
> $f(X, Y): R^{m×n}∘R^{m×n} → R^{m×n}$

$\begin{bmatrix}
x_{11} & \ldots & x_{1n}\\
\vdots & \ddots & \vdots \\ 
x_{m1} & \ldots & x_{mn}
\end{bmatrix}$∘
$\begin{bmatrix}
y_{11} & \ldots & y_{1n}\\
\vdots & \ddots & \vdots \\ 
y_{m1} & \ldots & y_{mn}
\end{bmatrix}$ =
$\begin{bmatrix}
x_{11}y_{11} & \ldots & y_{1k}\\
\vdots & \ddots & \vdots \\ 
y_{n1} & \ldots & y_{nk}
\end{bmatrix}$

**Lưu ý**: phép nhân này được sử dụng rất nhiều trong lĩnh vực Học
máy và Học sâu.

In [ ]:
X = np.array([1,2,3,4,5,6]).reshape((2,3))
Y = np.array([6,5,4,3,2,1]).reshape((2,3))
Z = np.multiply(X,Y) #hoặc Z = X*Y
print(Z)
print(Z.ndim, '; ', Z.shape)

[[ 6 10 12]
 [12 10  6]]
2 ;  (2, 3)


**Tạo vector cột dạng ma trận đặc biệt $R^{m*1}$**

In [ ]:
x = np.array([1,2,3,4,5]).reshape((5,1))
print(x)
print(x.ndim, '; ', x.shape)

[[1]
 [2]
 [3]
 [4]
 [5]]
2 ;  (5, 1)


**Lấy ra 1 vector hàng từ ma trận X và chuyển thành ma trận đặc
biệt dạng $R^{1*n}$**

In [ ]:
X = np.array([1,2,3,4,5,6]).reshape((2,3))
m = X.shape[0]
n = X.shape[1]
print('m = ', m, '; n = ', n)
x = X[0, :]
print(x)
print(x.ndim, '; ', x.shape)
x = x.reshape((1,n))
print(x)
print(x.ndim, '; ', x.shape)

m =  2 ; n =  3
[1 2 3]
1 ;  (3,)
[[1 2 3]]
2 ;  (1, 3)


**Lấy ra 1 vector cột từ ma trận X và chuyển thành ma trận đặc
biệt dạng $R^{m*1}$**

In [ ]:
X = np.array([1,2,3,4,5,6]).reshape((2,3))
m = X.shape[0]
n = X.shape[1]
print('m = ', m, '; n = ', n)
x = X[:,1]
print(x)
print(x.ndim, '; ', x.shape)
x = x.reshape((m,1))
print(x)
print(x.ndim, '; ', x.shape)

m =  2 ; n =  3
[2 5]
1 ;  (2,)
[[2]
 [5]]
2 ;  (2, 1)


**Xếp thêm 1 vector cột vào đầu ma trận: $x ∈ R^m$ hay $x ∈R^{m×1}, X ∈ R^{m×n},
X = [x, X]$**

In [ ]:
X =np.array([1,2,3,4,5,6,7,8,9,10,11,12]).reshape((4,3))
x = np.array([1,1,1,1]).reshape((4,1))
X = np.column_stack([x,X])
print(X)
print(X.ndim, '; ', X.shape)

[[ 1  1  2  3]
 [ 1  4  5  6]
 [ 1  7  8  9]
 [ 1 10 11 12]]
2 ;  (4, 4)


**Tách 1 ma trận data ban đầu gồm $n$ cột thành 1 ma trận con $X$
chứa các $n-1$ cột đầu tiên và 1 vector cột $y$ lấy ra từ cột cuối cùng
của data.**

In [ ]:
data = np.array([[10,22,13,1],
[9,6,5,0],
[8,12,4,1],
[6,5,7,0]])
X = data[:,:-1]
y = data[:,-1].reshape((data.shape[0], 1))
print(X)
print(X.ndim, '; ', X.shape)
print(y)
print(y.ndim, '; ', y.shape)

[[10 22 13]
 [ 9  6  5]
 [ 8 12  4]
 [ 6  5  7]]
2 ;  (4, 3)
[[1]
 [0]
 [1]
 [0]]
2 ;  (4, 1)


# **CÁC PHÉP TOÁN VỚI TENSOR HẠNG CAO ($N>=3$)**


> Do cấu trúc Tensor được dùng chủ yếu trong các bài toán Học sâu (deep learning), nên ở đây chỉ trình bày một số thao tác cơ bản như khởi tạo Tensor hạng cao (n ≥ 3), và các thao tác thêm vào/lấy ra các phần tử của Tensor để phục vụ mục đích cho bài tập đọc kho ảnh, lấy dữ liệu ảnh để nhận dạng ở mức độ cơ bản.

> Các phép toán với Tensor sẽ được giới thiệu đầy đủ ở học phần Học sâu.


**Tạo 1 tensor $T ∈ R^{m×n×k}$ với $m = 2, n = 2$ và $k = 3$, các giá trị 
được sinh ngẫu nhiên.**

In [ ]:
import numpy as np
m=2
n=2
k=3
T = np.random.randint(low=-5,
high=5,size=m*n*k).reshape(k,m,n)
print(T)

[[[-2 -2]
  [-3 -2]]

 [[-1  0]
  [-4 -1]]

 [[-2 -1]
  [-3 -1]]]


**Tạo 1 tensor $T2 ∈ R^{m×n×k×q}$ chứa 2 tensor $t1,t2 ∈ R^{m×n×k}$, biết $t1$ và $t2$ được sinh ngẫu nhiên**

In [ ]:
import numpy as np
m=2
n=2
k=3

t1 = np.random.randint(low=-5, high=5,size=m*n*k).reshape(k,m,n)
t2 = np.random.randint(low=-5, high=5,size=m*n*k).reshape(k,m,n)
t3 = np.random.randint(low=-5, high=5,size=m*n*k).reshape(k,m,n)
t4 = np.random.randint(low=-5, high=5,size=m*n*k).reshape(k,m,n)

T = np.stack((t1, t2, t3, t4), axis=-1)
print(T.shape)
x = T[:,:,:,0]
print(x.shape)
m1 = x[0,:,:]
print(m1)
print(m1.shape)

(3, 2, 2, 4)
(3, 2, 2)
[[-3  4]
 [-2  3]]
(2, 2)
