<a href="https://colab.research.google.com/github/hoangnuthuphuong/Machine_Learning/blob/main/Chuong3_HoiQuyTuyenTinhDaBien/BaiTapTaiLop1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

**1. Cho v là 1 vector hàng $v= [1,2,3,4,5]$**


Lưu ý: vector tương ứng với tensor hạng 1


In [8]:
# Tạo 1 vector
v = np.array([4, 2, 3, 6, 5])
print('v dimension: ', v.ndim)
print('v shape: ', v.shape)
print(v)


v dimension:  1
v shape:  (5,)
[4 2 3 6 5]


**2. Cho w là 1 vcetor cột $w= [1;2;3;4;5]$**

Lưu ý: vector cũng có thể biểu diễn như là tensor hạng 2 ở trường hợp đặc biệt là R^(m×1)


In [9]:
m = w.shape[0]
w = np.reshape(w, (m, 1))
print('w dimension: ', w.ndim)
print('w shape: ', w.shape)
print(w)


w dimension:  2
w shape:  (5, 1)
[[4]
 [2]
 [3]
 [6]
 [5]]


**3. (Hãy xác định số chiều (ndim), kích thước (shape) của 2 vector v và w; In 2 vector v và w ra màn hình; Nhận xét điểm khác biệt của kết quả)**

In [26]:
# Tạo 1 vector
v = np.array([4, 2, 3, 6, 5])
print('v dimension: ', v.ndim)
print('v shape: ', v.shape)
print(v)


v dimension:  1
v shape:  (5,)
[4 2 3 6 5]


In [27]:
#Tạo vetor dưới dạng ma trận mx1
m = v.shape[0]
w = np.reshape(v, (m, 1))
print('w dimension: ', w.ndim)
print('w shape: ', w.shape)
print(w)

w dimension:  2
w shape:  (5, 1)
[[4]
 [2]
 [3]
 [6]
 [5]]


**Nhận xét**

* vector v là chuyển vị của vector w và ngược lại
* vector v là vector hàng còn vector w là vector cột
* vector v chỉ có 1 chiều còn vector w có 2 chiều









**4. Cho $u$ và $w$ là 2 vector cột có kích thước $(m, 1)$. Hãy tạo ma trận $X$ bằng cách ghép 2 vector cột $u$ và $w$ lại với nhau $X= [u,w]$**


In [24]:
#Tạo ma trân v mx1, ma trận w lấy ở câu 3 
v = np.reshape([6, 2, 1, 4, 5], (m,1))
print('v dimension: ', v.ndim)
print('v shape: ', v.shape)
print(v)

v dimension:  2
v shape:  (5, 1)
[[6]
 [2]
 [1]
 [4]
 [5]]


In [12]:
#Ghép 2 vector w và v thành ma trận mx2
X = np.column_stack([w, v])
print('X dimension: ', X.ndim)
print('X shape: ', X.shape)
print(X)

X dimension:  2
X shape:  (5, 2)
[[4 6]
 [2 2]
 [3 1]
 [6 4]
 [5 5]]


In [13]:
#Cách ghép thứ 2
X = np.hstack([w, v])
print('X dimension: ', X.ndim)
print('X shape: ', X.shape)
print(X)

X dimension:  2
X shape:  (5, 2)
[[4 6]
 [2 2]
 [3 1]
 [6 4]
 [5 5]]


In [14]:
#Lấy ra vector w từ X
print('Lấy ra vector w từ X')
w_X = X[:, 0]
print('w_X dimension: ', w_X.ndim)
print(w_X.shape)
print(w_X)


Lấy ra vector w từ X
w_X dimension:  1
(5,)
[4 2 3 6 5]


**5. Tạo ma trận X**

In [31]:
X = np.array([[1, 2, 3, 4, 5],
              [6, 7, 8, 9, 2],
              [4, 5, 7, 2, 1]])
print('X dimension: ', X.ndim)
print('X shape: ', X.shape)
print(X)

X dimension:  2
X shape:  (3, 5)
[[1 2 3 4 5]
 [6 7 8 9 2]
 [4 5 7 2 1]]


In [21]:
X = np.array([1,2,3,4,5,6,7,8,9,2,4,5,7,2,1]).reshape(3,5)
print('X dimension: ', X.ndim)
print('X shape: ', X.shape)
print(X)

X dimension:  2
X shape:  (3, 5)
[[1 2 3 4 5]
 [6 7 8 9 2]
 [4 5 7 2 1]]


**6. Nhân ma trận X với vector v**

In [28]:
Z = np.dot(X, v)
print('Z dimension: ', Z.ndim)
print('Z shape: ', Z.shape)
print(Z)

Z dimension:  1
Z shape:  (3,)
[ 66 126  64]


**7. Nhân ma trận X với vector w**

In [29]:
Z = np.dot(X, w)
print('Z dimension: ', Z.ndim)
print('Z shape: ', Z.shape)
print(Z)


Z dimension:  2
Z shape:  (3, 1)
[[ 66]
 [126]
 [ 64]]


**8. Xét ma trận $X$ ở câu 5, hãy tìm ma trận chuyển vị của $X$, ký hiệu là $X^T$**

In [32]:
#Nhân ma trận Y với vector w_X
T = np.dot(X, w_X)
print('T dimension: ', T.ndim)
print('T shape: ', T.shape)
print(T)

T dimension:  1
T shape:  (3,)
[ 66 126  64]
