<a href="https://colab.research.google.com/github/hoangnuthuphuong/Machine_Learning/blob/main/Chuong3_HoiQuyTuyenTinhDaBien/BaiTapTaiLop2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Thư viện cần dùng 
import numpy as np

$X =
\begin{bmatrix}
1 & 2 & 3 & 4 & 5\\
6 & 7 & 8 & 9 & 2 \\
4 & 5 & 7 & 2 & 1
\end{bmatrix}$

**1.** Hãy chuyển ma trận X sang kích thước (5, 3)


In [2]:
X = np.array([[1, 2, 3, 4, 5],
              [6, 7, 8, 9, 2],
              [4, 5, 7, 2, 1]])
X = np.reshape(X, (5, 3))
print('dimension: ', X.ndim)
print('X shape: ', X.shape)
print(X)

dimension:  2
X shape:  (5, 3)
[[1 2 3]
 [4 5 6]
 [7 8 9]
 [2 4 5]
 [7 2 1]]


**2.** Hãy tạo vector cột sau:

$w= 
\begin{bmatrix}
2\\
4\\
2
\end{bmatrix}$

In [3]:
# Tạo vector trọng số w (3, 1)
w = np.reshape([2, 4, 2], (3, 1))
print('dimension: ', w.ndim)
print('w shape: ', w.shape)
print(w)

dimension:  2
w shape:  (3, 1)
[[2]
 [4]
 [2]]


**3.** Về lý thuyết, ta có: $ℎ_𝑤(𝑥) = 𝑤𝑋$
Tuy nhiên, với trường hợp cụ thể của X và w ở câu 2 & 3 thì giả thuyết $ℎ_𝑤(𝑥)$ được viết lại như sau: $ℎ_𝑤(𝑥) = 𝑋𝑤$


* Hãy viết mã lệnh tính $ℎ_𝑤(𝑥)$
* Xác định chiều (ndim), kích thước (shape) và in kết quả $ℎ_𝑤(𝑥)$ ra màn hình


In [11]:
# h = X.w
h = np.dot(X, w)
print('dimension: ', h.ndim)
print(h.shape)
print(h)

dimension:  2
(5, 1)
[[16]
 [40]
 [64]
 [30]
 [24]]


**4.** Từ công thức
$J(w)= \frac {1} {2m}$ $\sum_{i=1}^m (h_w(x_i)-y_i)^2$
Chuyển sang công thức viết theo dạng ma trận, ta có công thức tương đương sau
$J(w) = \frac {1} {2m} \sum(X.w-y)$ Hãy viết mã lệnh tính J(w) theo công thức tương đương

In [13]:
# Tao vector y (5, 1)
y= np.reshape([1,2, 3, 2, 1], (5, 1))

# Tính Xw - y hay h - y
hieu = h - y
print('dimension: ', hieu.ndim)
print(hieu.shape)
print(hieu)

dimension:  2
(5, 1)
[[15]
 [38]
 [61]
 [28]
 [23]]


**5.** Theo lý thuyết, công thức tính đạo hàm riêng là: $\frac{∂J(w)} {∂w_i} = \frac{1}{m} \sum_{i=1}^m (h_w(x_i)-y_i).x_i$ (3) Chuyển sang công thức viết theo dạng
ma trận, ta có công thức tương đương sau: $∇J(w) = \frac{1}{m} \sum X^T . (Xw-y)$  (4)

* Hãy viết mã lệnh tính ∇J(w) theo công thức
(4)

In [14]:
# Ở câu trên ta đã có hieu = Xw - y
# (h-y).X = (5x1).(5x3) --> (h - y).XT = (5x1).(3x5) 
h2 = np.dot(X.T, hieu)
print('dimension: ', h2.ndim)
print(h2.shape)
print(h2)

dimension:  2
(3, 1)
[[811]
 [866]
 [985]]


**6.** Theo thuật toán Gradient descent, các trọng số được cập nhật theo công thức
$w_i = w_i − α \frac{∂J(w)} {∂w_i} , ∀i$ (5)
Chuyển sang công thức viết theo dạng ma trận, ta có công thức tương đương
sau:
$w = w − α. ∇J(w)$ (6)
* Hãy viết mã lệnh tính w theo công thức (6)

In [19]:
alpha = 0.01
W = w - alpha*h2
print('dimension: ', W.ndim)
print(W.shape)
print(W)


dimension:  2
(3, 1)
[[-6.11]
 [-4.66]
 [-7.85]]
