<a href="https://colab.research.google.com/github/hoangnuthuphuong/Machine_Learning/blob/main/Chuong3_HoiQuyTuyenTinhDaBien/C3_BTVN3_SuDungLopLinearRegression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Quy tắc sử dụng chung mô hình hồi quy do sklearn cung cấp là:
- Bước 1: Khởi tạo mô hình
- Bước 2: Huấn luyện mô hình với tập dữ liệu (huấn luyện – sẽ được học ở bài 5) bằng hàm **fit()**
- Bước 3: Tiến hành dự đoán bằng hàm **predict()**

**Lưu ý:** đối với các mô hình do sklearn cung cấp thì vector y được xét ở không gian $R^m$ (chứ không phải $R^{m×1}$).

In [ ]:
import os
import numpy as np
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from sklearn.linear_model import LinearRegression

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


**DỮ LIỆU BAN ĐẦU**

In [ ]:
data = np.loadtxt(os.path.join("/content/drive/MyDrive/Classroom/Học máy 1 Phần cơ sở", "ex1data2.txt"),delimiter=",")
print('Kích thước của tập dữ liệu: ', data.shape)
X = data[:, :-1]
print('\nX shape: ', X.shape)
print(X[:5])
y = data[:, -1].reshape(-1, 1)
print('\ny shape: ', y.shape)
print(y[:5])

Kích thước của tập dữ liệu:  (47, 3)

X shape:  (47, 2)
[[2.104e+03 3.000e+00]
 [1.600e+03 3.000e+00]
 [2.400e+03 3.000e+00]
 [1.416e+03 2.000e+00]
 [3.000e+03 4.000e+00]]

y shape:  (47, 1)
[[399900.]
 [329900.]
 [369000.]
 [232000.]
 [539900.]]


**MinMaxScaler**

In [ ]:
print('Thực hiện MinMaxScaler')
#Khởi tạo bộ điều chỉnh dữ liệu
scaler = MinMaxScaler()
#Phải thực hiện thao tác fit(data) trước khi điều chỉnh dữ liệu
scaler.fit(data)
#Thực hiện điều chỉnh dữ liệu
D = scaler.transform(data)
print('Lấy ra tập dữ liệu X, y')
X, y = D[:,:-1], D[:, -1]
print('\nX shape: ', X.shape)
print(X[:5])
y = data[:, -1].reshape(-1, 1)
print('\ny shape: ', y.shape)
print(y[:5])

Thực hiện MinMaxScaler
Lấy ra tập dữ liệu X, y

X shape:  (47, 2)
[[0.34528406 0.5       ]
 [0.20628792 0.5       ]
 [0.42691671 0.5       ]
 [0.1555433  0.25      ]
 [0.59238831 0.75      ]]

y shape:  (47, 1)
[[399900.]
 [329900.]
 [369000.]
 [232000.]
 [539900.]]


**StandardScaler**

In [52]:
print('Thực hiện StandardScaler')
#Khởi tạo bộ điều chỉnh dữ liệu
scaler = StandardScaler()
#Phải thực hiện thao tác fit(data) trước khi điều chỉnh dữ liệu
scaler.fit(data)
#Thực hiện điều chỉnh dữ liệu
D = scaler.transform(data)
print('Lấy ra tập dữ liệu X, y')
X, y = D[:,:-1], D[:, -1]
print('\nX shape: ', X.shape)
print(X[:5])
y = data[:, -1].reshape(-1, 1)
print('\ny shape: ', y.shape)
print(y[:5])

Thực hiện StandardScaler
Lấy ra tập dữ liệu X, y

X shape:  (47, 2)
[[ 0.13141542 -0.22609337]
 [-0.5096407  -0.22609337]
 [ 0.5079087  -0.22609337]
 [-0.74367706 -1.5543919 ]
 [ 1.27107075  1.10220517]]

y shape:  (47, 1)
[[399900.]
 [329900.]
 [369000.]
 [232000.]
 [539900.]]


**Training LinearRegression**

In [ ]:
print('Huấn luyện mô hình LinearRegression')
#Khởi tạo mô hình
model = LinearRegression()
#Huấn luyện mô hình với tập dữ liệu X, y
model.fit(X,y)
#Bộ trọng số tối ưu:
print('\t\tw optimal: ', model.coef_)

Huấn luyện mô hình LinearRegression
		w optimal:  [[109447.79646964  -6578.35485416]]


**DỰ ĐOÁN**

In [49]:
X_predict = model.predict(X)
print(X_predict[:10])

[[356283.1103389 ]
 [286120.93063401]
 [397489.46984812]
 [269244.1857271 ]
 [472277.85514636]
 [330979.02101847]
 [276933.02614885]
 [262037.48402897]
 [255494.58235014]
 [271364.59918815]]
